import { NextResponse } from 'next/server';
import connectMongo from '@/lib/conn';
import Mobil from '@/models/Mobil';

export async function GET() {
  try {
    await connectMongo();
    console.log('MongoDB Connected');

    const mobilSeed = [
      {
        merek: "Toyota",
        tipe: "Avanza G",
        tahun: "2021",
        transmisi: "automatic",
        warna: "Hitam",
        noPol: "B 1234 XYZ",
        noRangka: "MHKG1234XYZ00001",
        noMesin: "1NRFE123456",
        kapasitas_mesin: 1300,
        bahan_bakar: "Bensin",
        pajak: "2025-10-01",
        kilometer: 20000,
        dp: 20000000,
        angsuran_4_thn: 2500000,
        angsuran_5_tahun: 2200000,
        STNK: "ada",
        BPKB: "ada",
        Faktur: "ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :2000000
      },
      {
        merek: "Honda",
        tipe: "Brio RS",
        tahun: "2020",
        transmisi: "manual",
        warna: "Merah",
        noPol: "B 5678 ABC",
        noRangka: "MHGH4567ABC00002",
        noMesin: "L12B123457",
        kapasitas_mesin: 1200,
        bahan_bakar: "Bensin",
        pajak: "2026-01-15",
        kilometer: 30000,
        dp: 18000000,
        angsuran_4_thn: 2200000,
        angsuran_5_tahun: 1900000,
        STNK: "ada",
        BPKB: "ada",
        Faktur: "tidak ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: []
        ,
        harga :1300000
      },
      {
        merek: "Daihatsu",
        tipe: "Xenia R",
        tahun: "2019",
        transmisi: "manual",
        warna: "Silver",
        noPol: "B 9012 DEF",
        noRangka: "MHKG7890DEF00003",
        noMesin: "3SZVE789456",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2025-08-01",
        kilometer: 45000,
        dp: 16000000,
        angsuran_4_thn: 2100000,
        angsuran_5_tahun: 1800000,
        STNK: "tidak ada",
        BPKB: "ada",
        Faktur: "ada",
        status: "terjual",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :8800000
      },
      {
        merek: "Suzuki",
        tipe: "Ertiga GL",
        tahun: "2022",
        transmisi: "automatic",
        warna: "Putih",
        noPol: "B 3456 GHI",
        noRangka: "MHKF1234GHI00004",
        noMesin: "K15B123458",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2026-03-10",
        kilometer: 15000,
        dp: 21000000,
        angsuran_4_thn: 2600000,
        angsuran_5_tahun: 2300000,
        STNK: "ada",
        BPKB: "tidak ada",
        Faktur: "ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :19000000
      },
      {
        merek: "Nissan",
        tipe: "Livina VE",
        tahun: "2020",
        transmisi: "triptonic",
        warna: "Abu-Abu",
        noPol: "B 7890 JKL",
        noRangka: "MHKN1234JKL00005",
        noMesin: "HR15123459",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2025-12-20",
        kilometer: 35000,
        dp: 19000000,
        angsuran_4_thn: 2400000,
        angsuran_5_tahun: 2100000,
        STNK: "ada",
        BPKB: "ada",
        Faktur: "ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: []
        ,
        harga :900000000
      },
      {
        merek: "Mitsubishi",
        tipe: "Xpander Sport",
        tahun: "2021",
        transmisi: "automatic",
        warna: "Hitam",
        noPol: "B 1111 ZZZ",
        noRangka: "MHKM1111ZZZ00006",
        noMesin: "4A91123460",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2025-09-30",
        kilometer: 28000,
        dp: 23000000,
        angsuran_4_thn: 2700000,
        angsuran_5_tahun: 2400000,
        STNK: "tidak ada",
        BPKB: "ada",
        Faktur: "tidak ada",
        status: "terjual",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :1000000000000
      },
      {
        merek: "Toyota",
        tipe: "Rush TRD",
        tahun: "2018",
        transmisi: "manual",
        warna: "Putih",
        noPol: "B 4321 MNO",
        noRangka: "MHKG4321MNO00007",
        noMesin: "2NR123461",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2025-11-15",
        kilometer: 55000,
        dp: 17000000,
        angsuran_4_thn: 2000000,
        angsuran_5_tahun: 1750000,
        STNK: "ada",
        BPKB: "ada",
        Faktur: "ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :56500000
      },
      {
        merek: "Honda",
        tipe: "CR-V Prestige",
        tahun: "2023",
        transmisi: "automatic",
        warna: "Silver",
        noPol: "B 9999 PQR",
        noRangka: "MHGH9999PQR00008",
        noMesin: "K20C123462",
        kapasitas_mesin: 2000,
        bahan_bakar: "Bensin",
        pajak: "2026-06-01",
        kilometer: 7000,
        dp: 40000000,
        angsuran_4_thn: 5000000,
        angsuran_5_tahun: 4500000,
        STNK: "ada",
        BPKB: "ada",
        Faktur: "ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :24532000
      },
      {
        merek: "Wuling",
        tipe: "Confero S",
        tahun: "2019",
        transmisi: "manual",
        warna: "Abu-Abu",
        noPol: "B 2468 STU",
        noRangka: "MHKW2468STU00009",
        noMesin: "L2B123463",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2025-07-01",
        kilometer: 60000,
        dp: 14000000,
        angsuran_4_thn: 1800000,
        angsuran_5_tahun: 1600000,
        STNK: "tidak ada",
        BPKB: "tidak ada",
        Faktur: "ada",
        status: "terjual",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: []
        ,harga :49982000
      },
      {
        merek: "Hyundai",
        tipe: "Stargazer Prime",
        tahun: "2023",
        transmisi: "triptonic",
        warna: "Biru",
        noPol: "B 7777 VWX",
        noRangka: "MHKH7777VWX00010",
        noMesin: "G4FJ123464",
        kapasitas_mesin: 1500,
        bahan_bakar: "Bensin",
        pajak: "2026-02-10",
        kilometer: 5000,
        dp: 30000000,
        angsuran_4_thn: 3500000,
        angsuran_5_tahun: 3100000,
        STNK: "ada",
        BPKB: "tidak ada",
        Faktur: "tidak ada",
        status: "tersedia",
        deskripsi: "Bebas laka banjir, KM asli , pajak panjang body full ngaleng",
        fotos: [],
        harga :100000000
      }
    ];

    await Mobil.deleteMany({});
    const result = await Mobil.insertMany(mobilSeed);
    console.log('Mobil inserted:', result);

    return NextResponse.json({ message: 'Data mobil berhasil ditambahkan' });
  } catch (error: any) {
  console.error('Error seeding mobil:', error.message);
  console.error('Stack:', error.stack);
  return NextResponse.json({ error: 'Gagal insert mobil' }, { status: 500 });
}
}
